name: 'Lint and Format Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint and Format Python Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8

    - name: Auto-fix Python Code Issues
      run: |
        # This command runs autopep8 to automatically fix PEP8 issues
        find . -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +
        echo "Autopep8 has fixed Python files successfully"

    - name: Lint Python Files
      run: |
        # This command finds all Python files recursively and runs flake8 on them
        find . -name "*.py" -exec flake8 {} +
        echo "Linted all Python files successfully"


  lint_js:
    name: Lint and Format JavaScript Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install eslint prettier --save-dev

    - name: Auto-fix JavaScript Code Issues with ESLint and Prettier
      run: |
        # Run ESLint with --fix to auto-correct issues
        npx eslint './**/*.js' --fix --ext=.js
        # Run Prettier to ensure consistent code formatting
        npx prettier --write './**/*.js'
        echo "Auto-fix applied with ESLint and Prettier"

    - name: Run ESLint to Check for Errors
      run: |
        # This command runs ESLint on JavaScript files
        npx eslint './**/*.js' --ext .js || true
        echo "Linted all JavaScript files successfully"
